export const CATEGORY_FETCH = 'CATEGORY_FETCH';
export const CHANGE_LAT_LONG = 'CHANGE_LAT_LONG';
export const CHANGE_LACATION_INPUT = 'CHANGE_LACATION_INPUT';
export const LOCATION_SELECTED = 'LOCATION_SELECTED';
export const MAKE_LOCATION_AJAX = 'MAKE_LOCATION_AJAX';